### ISSUE TITLE
How to use input.py

### ISSUE THREAD

**Issue by yihongyuelan** [Swind/pure-python-adb#11]
Now I use device.shell('input keyevent KEYCODE_POWER'), can u show me some usages? 
Thanks a lot

**Comment by Swind** [comment]
Hi yihongyuelan:
The `input.py` is just a wrapper for the `input` shell command.
For example, the command you used `input keyevent KEYCODE_POWER`

```python
device.shell('input keyevent KEYCODE_POWER')
```
You can replace it by 

```python
device.input("KEYCODE_POWER")
```

`input text "test"` is

```python
device.input_text("test")
```
I hope it will help you somehow
Thanks

**Comment by yihongyuelan** [comment]
Thanks a lot
