### ISSUE TITLE
Motorola Z do not support "pm install"

### ISSUE THREAD

**Issue by yihongyuelan** [Swind/pure-python-adb#12]
Thanks for your awesome project.

My cell phone is Motorola Z (XT1650-05 / Android 8.0.0 / System OCC27.102-23), it will throw error "[[INSTALL_FAILED_TEST_ONLY: installPackageLI]]". Install commands as below:
adb push app-debug.apk /data/local/tmp
adb shell pm install -t -r /data/local/tmp/app-debug.apk

I found it's a OS BUG from Lenovo BBS, and the offical solution is:
adb install -t -r app-debug.apk

I found some adb commands (eg:logcat) do not implement in this project, and I wonder maybe "logcat" is same as "install",  can you share some advice?

BR

**Comment by Swind** [comment]
Sorry for late reply.

The interface of the `install` function

```python
 def install(self, path,
                forward_lock=False,  # -l
                reinstall=False,  # -r
                test=False,  # -t
                installer_package_name=False,  # -i
                shared_mass_storage=False,  # -s
                internal_system_memory=False,  # -f
                downgrade=False,  # -d
                grand_all_permissions=False  # -g
                )
```

The  `install -t -r app-debug.apk` = `device.install("app-debug.apk", test=True, reinstall=True)`
