### ISSUE TITLE
screencap 生成的图片不能识别

### ISSUE THREAD

**Issue by demidroid** [Swind/pure-python-adb#15]
截取的图片，有的设备上的可以识别，有的设备上的不能识别

**Comment by Swind** [comment]
你好，請問方便提供我一張不能識別的圖片嗎？
我猜應該跟之前的問題一樣，以前的 Android 某些版本用 shell 執行 screencap 的時候，
會多出 /r/n 等字元，雖然我有處理了，但是可能還有些問題。
所以如果可以提供我一張不能識別的圖的話，我可能比較好針對這個來處理。

另外如果方便的話也可以提供給我不能識別的設備的型號跟 Android 版本嗎？

謝謝你
