### ISSUE TITLE
shell command blocking

### ISSUE THREAD

**Issue by m00dy-** [Swind/pure-python-adb#2]
Hello,
First of all thank you for your lib is so helpful.
However, I'm having a tiny issue when I attempt to launch a process as : 
device.shell("/system/bin/sh"). My code is then blocked. 

Any help ?

**Comment by Swind** [comment]
Sorry about the late response.
Because when you launch "/system/bin/sh" , the command will not complete and will enter interactive mode.
So the device.shell("/system/bin/sh") will block the process.
