### ISSUE TITLE
Name conflict with Google's adb package

### ISSUE THREAD

**Issue by JeffLIrion** [Swind/pure-python-adb#21]
Google's [adb](https://github.com/google/python-adb) package also uses the name `adb`, and so these packages can't be used together. To get around this for my `androidtv` package (which is used by Home Assistant), I forked your repo and renamed the package from `adb` to `adb_messenger`. 

Any chance you'd be willing to rename the package from `adb` to something else?

**Comment by Swind** [comment]
sorry for late reply
I will change the package name from `adb` to `ppadb` (pure python adb).
Thanks

**Comment by JeffLIrion** [comment]
Thanks! 👍
