### ISSUE TITLE
device.shell(dumpsys meminfo)耗时超过500ms

### ISSUE THREAD

**Issue by testerclub** [Swind/pure-python-adb#24]
在实际使用过程中，发现执行meminfoContext = self.device.shell(dumpsys meminfo)，获取系统所有进程内存数据时，耗时超过500ms，不知道是不是因为socket通信效率太低导致

**Comment by Swind** [comment]
你好，如果你使用 `adb shell dumpsys meminfo` 執行的時候時間大約是多少呢？
我想知道一下大約差多少。

Thanks

**Comment by testerclub** [comment]
使用adb shell手动执行，耗时更多，我是希望self.device.shell(dumpsys meminfo)能耗时更短

**Comment by Swind** [comment]
那個就沒有辦法了
因為慢是慢在 `dumpsys meminfo` 這個指令上面。
你可以 `adb shell` 連進去之後
下 `time dumpsys meminfo` 你就可以看到 `dumpsys meminfo` 這個指令本身花了多少時間了
