### ISSUE TITLE
Support custom functions

### ISSUE THREAD

**Issue by williamfzc** [Swind/pure-python-adb#3]
你好~
很高兴终于有人打算做这个东西了，看起来确实很不错
近期我也在做一个类似的东西 [pyatool](https://testerhome.com/topics/16673)，主要为了解决在开发中频繁使用恶心的subprocess的问题；
想问一下，是否考虑支持让用户自定义函数？类似：

```python
def download_and_install(url, toolkit=None):
    resp = requests.get(url)
    if not resp.ok:
        return False
    with tempfile.NamedTemporaryFile('wb+', suffix='.apk', delete=False) as temp:
        temp.write(resp.content)
        temp.close()
        toolkit.adb.run(['install', '-r', '-d', '-t', temp.name])
        os.remove(temp.name)
    return True


PYAToolkit.bind_func(real_func=download_and_install)

# and
device_toolkit = PYAToolkit('123456F')
device_toolkit.download_and_install()
```

似乎能覆盖更多的场景 ：）

另外，如果导入方式是：

```python
from adb.client import Client as AdbClient
```

会与google提供的[python-adb](https://github.com/google/python-adb)冲突~

**Comment by Swind** [comment]
你好
關於 custom functions 的部份，
我想在設計上目前這個 `pure-python-adb` 比較合適的角色是在你的範例程式碼裡面的

```
toolkit.adb.run(['install', '-r', '-d', '-t', temp.name])
```
中 `toolkit.adb` 這個地位，屬於最底層的工具 library，所以我想我應該不會在 `pure-python-adb` 中加上這個功能。

這功能比較合適的的層級應該就是你所開發的 `pyatool` 這種 library 的層級，
比較上層，對使用者包裝底下實際操作的部份。
也就是包裝 `使用 subprocess` 或者 `使用 socket` 跟 `adb server` 溝通的實際操作部份


關於 `package name` 這我當初也沒有注意到跟 google 的 python-adb 重複了，
只是現在也沒救了 Orz 因為我自己的很多測試已經大量使用這個 library 了。
改了我會崩潰，哈哈
所以應該會維持這樣

謝謝你的建議
