### ISSUE TITLE
Could you add method to start adb server?

### ISSUE THREAD

**Issue by rusnackor** [Swind/pure-python-adb#36]
I am very new to ADB and Android development. But I do work abit with python. I really apprecitae that this library can do all the stuff in single python script. However, I was getting this error:

        devices = client.devices()
      File "/home/rrr/.local/lib/python2.7/site-packages/ppadb/command/host/__init__.py", line 23, in devices
        result = self._execute_cmd(cmd)
      File "/home/rrr/.local/lib/python2.7/site-packages/ppadb/command/host/__init__.py", line 13, in _execute_cmd
        with self.create_connection() as conn:
      File "/home/rrr/.local/lib/python2.7/site-packages/ppadb/client.py", line 14, in create_connection
        conn.connect()
      File "/home/rrr/.local/lib/python2.7/site-packages/ppadb/connection.py", line 41, in connect
        e
    RuntimeError: ERROR: connecting to 127.0.0.1:5037 [Errno 111] Connection refused.
    Is adb running on your computer?

And it took me pretty long time to find out how to fix it. Plus, I do not like the fact, that there is nothing about adb server starting on your machine in examples and at all in README.

Is it possible to add method, that we can call for starting adb server?

To make it like this:
    
    client = AdbClient(host="127.0.0.1", port=5037)
    if ppadb.adb_server_not_running():
        ppadb.start_adb_server()
    devices = client.devices()

I am pretty sure, many people starting with ADB would really apprecitae this.

**Comment by Swind** [comment]
Hi @rusnackor 

Sorry, because this package is a pure adb client, it should not run/start the adb server.
And I don't want to execute the `adb` command in this package.

Thanks for your issue.
