### ISSUE TITLE
Root Command Doesn't Return

### ISSUE THREAD

**Issue by DougSteiert** [Swind/pure-python-adb#37]
Is there a way to fix when calling "su" with device.shell() method? I am noticing when I call that command to assume root, that the rest of the script does not execute. 

I imagine one workaround would just to perform "su [rest of command]" so it returns the command output, but being able to just perform "su" to take over as root for the rest of commands is beneficial for modularization, in my case at least.

*Update: calling "su echo hello world" for example actually did not work. I have a handler assigned to these shell calls, and issuing the "su" does output that I correctly assumed root, but no further commands issue and the script just hangs, as if it's waiting...

**Comment by ebisek-logi** [comment]
These appear to be two different issues. The title states that root command doesn't return. 
In Android the su command is very restricted and does not work the same as the 'adb root' command.

The root command is found in: command/transport/__init__.py

The implementation of the root method is not as solid as I would like it to be. For example, it does not currently handle the case if/when the adb is already in root mode.

**Comment by DougSteiert** [comment]
I'm going to take @ebisek-logi's reply as the answer. I have long moved on from this project and had found another workaround for this.

**Comment by tolgatasci** [comment]
you can try
https://github.com/Swind/pure-python-adb/issues/78#issuecomment-990082629
