### ISSUE TITLE
wait_boot_completed command has wrong timeout calculation

### ISSUE THREAD

**Issue by ebisek-logi** [Swind/pure-python-adb#38]
Hello, 
wait_boot_completed in transport/__init__.py has an incorrect timeout calculation.

In particular:
        end_time = time.time() + timeout * 1000

timeout is defined as a value in seconds. time.time() returns a floating point value in seconds. Therefore the multiplication by 1000 is incorrect, and causes major hang-up issues if you do an adb reboot and want to hold up your script from doing anything until boot_completed is reached and the reboot fails to complete.

Can this line be fixed to:
        end_time = time.time() + timeout

Thanks,
Edwin

**Comment by Swind** [comment]
I will fix it as soon as possible. Thanks for issue.
