### ISSUE TITLE
[feature] report progress during push

### ISSUE THREAD

**Issue by lk-chen** [Swind/pure-python-adb#39]
The Android ADB impl has [ReportProgress](https://github.com/aosp-mirror/platform_system_core/blob/46f281edf5e78a51c5c1765460cddcf805e88d48/adb/client/file_sync_client.cpp#L149) to report progress during file transfer.

I'm proposing a new argument `progress` in Sync.push(), similar to [scp](https://github.com/jbardin/scp.py/blob/master/scp.py#L98), allowing users to pass a callback and e.g. print progress on screen.

**Comment by lk-chen** [comment]
Ah, didn't notice #31

**Comment by Swind** [comment]
Thanks your pull request !!!!!!!!!!
