### ISSUE TITLE
push does not preserve original timestap unlike equiv adb push from command line

### ISSUE THREAD

**Issue by LinkOne1A** [Swind/pure-python-adb#4]
Hello;
On linux, adb push will preserve the file modify and access time, per example below:
```
$ adb push doc1.pdf /sdcard/Documents/sync-2
4331 KB/s (298200 bytes in 0.067s)
```

```
$ adb shell stat /sdcard/Documents/sync-2/doc1.pdf
  File: `/sdcard/Documents/sync-2/doc1.pdf'
  Size: 298200	 Blocks: 584	 IO Blocks: 512	regular file
Device: 15h/21d	 Inode: 1344393	 Links: 1
Access: (660/-rw-rw----)	Uid: (    0/    root)	Gid: ( 1015/sdcard_rw)
Access: 2018-04-27 04:30:18.000000000
Modify: 2018-04-27 04:30:18.000000000
Change: 2018-12-30 13:21:16.527000210
```

But calling device.push() will not, it resets all time stamps to the copy time. Here is the same file but copied to android using device.push():
```
  File: `/sdcard/Documents/sync-2/doc1.pdf'
  Size: 298200	 Blocks: 584	 IO Blocks: 512	regular file
Device: 15h/21d	 Inode: 1344394	 Links: 1
Access: (660/-rw-rw----)	Uid: (    0/    root)	Gid: ( 1015/sdcard_rw)
Access: 2018-12-30 13:26:13.000000000
Modify: 2018-12-30 13:26:13.000000000
Change: 2018-12-30 13:26:11.077000227

```

I think this is an important bug to fix IMHO, as it prevents writing code to sync files between an android device and a desktop.

Thank you.

**Comment by Swind** [comment]
Hi LinkOne1A:

I can't reproduce the result

```
>>> stat screen.png                                                                                                                                                                                                         
  File: 'screen.png'
  Size: 390465          Blocks: 768        IO Block: 4096   regular file
Device: 812h/2066d      Inode: 12210168    Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1000/   swind)   Gid: ( 1000/   swind)
Access: 2019-01-08 20:19:42.096859016 +0800
Modify: 2018-07-08 01:21:29.676948958 +0800
Change: 2019-01-08 20:18:16.965345445 +0800
 Birth: -
```
```
>>> date;adb push screen.png /sdcard/screen.png                                                                                                                                                                             
Tue Jan  8 20:21:18 CST 2019
screen.png: 1 file pushed. 187.5 MB/s (390465 bytes in 0.002s)
```
```
>>> adb shell stat /sdcard/screen.png                                                                                                                                                                                       
  File: `/sdcard/screen.png'
  Size: 390465   Blocks: 768     IO Blocks: 4096        regular file
Device: 13h/19d  Inode: 60       Links: 1
Access: (660/-rw-rw----)        Uid: (0/    root)       Gid: (1015/sdcard_rw)
Access: 2019-01-08 20:21:18.034000000
Modify: 2019-01-08 20:21:18.034000000
Change: 2019-01-08 20:21:18.034000000
```
My adb version is 

```
>>> adb version
Android Debug Bridge version 1.0.40
Version 4986621
Installed as /home/swind/Android/Sdk/platform-tools/adb
```

Your adb version is ?

Thanks

**Comment by LinkOne1A** [comment]
Hi Swind;

If I am correct, you are making the observation that adb push does not preserve the time stamp either, hence you comment that you can not reproduce the result. Am I correct?

If so, assuming that is your point, then I have a hunch what might be going on.

I had an android tablet OS version 8.0, where adb push did preserve the time stamp of files copied from Linux to android. I had to return the tablet so i don't have that tablet anymore. However, I just tried adb push on a tablet that is running android version 7.0, and time stamp was not preserved..

So I think a more precise statement of the problem I observed is this:
On an android OS=8.0 device, adb push does preserve file time stamp but this python lib does not.

I will try to see if I can find another android device running OS=8.0 to try this out.

Thank you for looking into this problem.

**Comment by LinkOne1A** [comment]
**[On the linux side -------------------------------------------------]**

admin$ ls -l portege_R600-S4212.pdf
-rw-r--r-- 1 admin admin 75027 Apr 27  2018 portege_R600-S4212.pdf

admin$ stat portege_R600-S4212.pdf
  File: 'portege_R600-S4212.pdf'
  Size: 75027           Blocks: 152        IO Block: 4096   regular file
Device: fd01h/64769d    Inode: 39851738    Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1000/   admin)   Gid: ( 1000/   admin)
Access: 2018-12-04 06:39:35.615283016 -0800
Modify: 2018-04-27 01:24:55.270224841 -0700
Change: 2018-04-27 01:24:55.270224841 -0700
 Birth: -

admin$ adb push portege_R600-S4212.pdf /sdcard/Documents
1513 KB/s (75027 bytes in 0.048s)

**[On the android side, OS=9, device=Pixel ---------------------------]**

admin$ adb shell stat /sdcard/Documents/portege_R600-S4212.pdf
  File: `/sdcard/Documents/portege_R600-S4212.pdf'
  Size: 75027    Blocks: 160     IO Blocks: 512 regular file
Device: 19h/25d  Inode: 920163   Links: 1
Access: (660/-rw-rw----)        Uid: (    0/    root)   Gid: ( 1015/sdcard_rw)
Access: 2018-04-27 01:24:55.000000000
Modify: 2018-04-27 01:24:55.000000000
Change: 2019-01-15 08:25:30.703755984

admin$ adb version
Android Debug Bridge version 1.0.32

admin$ adb shell getprop ro.build.version.release 
9

admin$ adb shell getprop ro.build.version.sdk 
28

**[Observation re above results: the 'Modify' time is preserved ------]**

[Below,  another device, nvidia shield, **OS=7** -----------------------]

admin$ adb shell getprop ro.build.version.release
7.0

admin$ adb shell getprop ro.build.version.sdk
24

admin$ adb push portege_R600-S4212.pdf /sdcard/Documents/
3389 KB/s (75027 bytes in 0.021s)

admin$ adb shell stat /sdcard/Documents/portege_R600-S4212.pdf
  File: `/sdcard/Documents/portege_R600-S4212.pdf'
  Size: 75027    Blocks: 152     IO Blocks: 4096        regular file
Device: 12h/18d  Inode: 5240     Links: 1
Access: (660/-rw-rw----)        Uid: (0/    root)       Gid: (1015/sdcard_rw)
Access: 2019-01-15 08:44:33.772999988
Modify: 2019-01-15 08:44:33.783999988
Change: 2019-01-15 08:44:33.783999988

**[Observations -----------------------------------------------------]**
The 'Modify' time stamp is preserved on the Pixel device OS=9
The 'modify' time stamp is NOT preserved on tablet device OS=7
My original test was on an unknown tablet OS=8, where the Modify time stamp was also preserved.

So there seems to be two components to this issue:
1) The python lib being discussed here does not preserve the (Modify) time stamp on any target OS.
2) The 'Modify' time stamp is preserved by adb push only on OS>=8

Thank you for looking into this problem.

**Comment by Swind** [comment]
Hi LinkOne1A:

Thank you very much !
Yes, because the adb [sync](https://android.googlesource.com/platform/system/core/+/master/adb/SYNC.TXT)  doesn't provide the parameters to set the access time, modify time and change time. 

So I think this is preserved by `adb client` and I need to modify the timestamp by myself.
I want to find the `command` the `adb client` used in the android source code. 
But I can't reproduce the result ......... 

Thanks for your detail reply. This is definitely cleaner and I know how to fix this.
It's very helpful !

I'll try to fix this ASAP

Thank you
