### ISSUE TITLE
API call hangs

### ISSUE THREAD

**Issue by G-R-A-F-F** [Swind/pure-python-adb#42]
Hi,
Issue core methods to get access to device API hangs and never finish.

Python code:
from ppadb.client import Client
adb = Client(host='192.168.0.123', port=5556)
devices = adb.devices() #Never passes this line, hangs forever
print(devices.version()) #Same, never passes this line, hangs forever

Shell:
$adb connect 192.168.0.123:5556
 daemon not running; starting now at tcp:5037
 daemon started successfully
connected to 192.168.0.123:5556
$adb shell input touchscreen swipe 500 500 500 900 200
Scroll Event Works

Troubleshooting:
Reinstalled ADB:
$sudo aptitude reinstall adb

reinstalled pure-python-adb:
$pip3 install pure-python-adb -U --no-cache-dir 

noting helped...

**Comment by ebisek-logi** [comment]
Is there a specific reason why you are using port 5556.

the default is 5555

From the android documentation:
Emulator 1, console: 5554
Emulator 1, adb: 5555
Emulator 2, console: 5556
Emulator 2, adb: 5557

So for proper adb connection use 5555

**Comment by G-R-A-F-F** [comment]
I tried port 5555 at the beginning and just tried it one more time. The results are identical as I described above.

**Comment by ebisek-logi** [comment]
I shoot, I see what is wrong. The client initialization is with the adb server inside your host computer. so instead of:
> Python code:
> from ppadb.client import Client
> adb = Client(host='192.168.0.123', port=5556)
> devices = adb.devices() #Never passes this line, hangs forever
> print(devices.version()) #Same, never passes this line, hangs forever
> 
try this:

from ppadb.client import Client
adb = Client(host='127.0.0.1', port=5037)
devices = adb.devices() 
print(devices[0].serial)

**Comment by G-R-A-F-F** [comment]
Thank you this works. Does this means that wireles conections are not supported?

**Comment by ebisek-logi** [comment]
No, I don't see why that would be any different.

Here is how the connection would be with wireless  (ie adb over IP)
```
from ppadb.client import Client
adb = Client(host='127.0.0.1', port=5037)
devices = adb.devices()
print(devices[0].serial)
devserial = devices[0].serial
if ':' in devserial:
    # the device is connected over IP
    host = devserial.split(':')[0]
    port = int(devserial.split(':')[1])
    if adb.remote_connect(host, port) is True:
           print('Successful TCP/IP connection to device')
    else:
           exit()
adbdev = adb.device(devserial)
print(adbdev.get_properties())
```

**Comment by G-R-A-F-F** [comment]
Perfect! Thanks again!

**Comment by ebisek-logi** [comment]
cheers. I use ppadb for all our automation and it is not perfect, but it is the best one I have found thus far. 
I wish I could be a contributor, as we are customizing it a lot for ourselves in-house.
