### ISSUE TITLE
Async version?

### ISSUE THREAD

**Issue by JeffLIrion** [Swind/pure-python-adb#43]
Any chance of adding async support or creating an async version of this package?

**Comment by ebisek-logi** [comment]
Are there particular calls that you believe are useful in async version?

For example, adb devices in async form seems pretty useless to me.
I can however see a case for certain other commands to be async

**Comment by JeffLIrion** [comment]
> Are there particular calls that you believe are useful in async version?
> 
> For example, adb devices in async form seems pretty useless to me.
> I can however see a case for certain other commands to be async

My use cases is the [Android TV integration in Home Assistant](https://www.home-assistant.io/integrations/androidtv/). 

Currently, it uses the [`androidtv`](https://github.com/JeffLIrion/python-androidtv) package, which uses `pure-python-adb` as one of its two means of sending ADB commands; the other is [`adb-shell`](https://github.com/JeffLIrion/adb_shell). This is all sync, and Home Assistant runs all these commands in its thread pool. 

I've ported the `androidtv` and `adb-shell` packages to async ([`aio-androidtv`](https://github.com/JeffLIrion/aio-androidtv) and [`aio-adb-shell`](https://github.com/JeffLIrion/aio_adb_shell)). An async version of `pure-python-adb` would enable the Home Assistant integration to be fully async. 

And given that this package is all about socket I/O, converting it to async would yield an improvement in efficiency.
