### ISSUE TITLE
Rename or don't install tools package?

### ISSUE THREAD

**Issue by martijnthe** [Swind/pure-python-adb#45]
Thanks for ppadb! So far it has been very useful.

I noticed ppadb install a package called `tools` into `site_packages`.
It's a minor thing, but perhaps rename it to something less generic / common?

In our use case, it was causing conflicts with a project-local module called `tools`.

**Comment by Swind** [comment]
Hi @martijnthe 

Thank you.
You are right, I should not install the `tools` package.
I will remove it !
