### ISSUE TITLE
error:device.forward("tcp:10808", "tcp:10808") 

### ISSUE THREAD

**Issue by ztoiax** [Swind/pure-python-adb#48]
output:
AttributeError: 'NoneType' object has no attribute 'forward'

**Comment by Swind** [comment]
Hi @ztoiax 
Could you provide more detail code about the `device` ?
`device` is `None` means that the device cannot be found on adb server.

**Comment by ztoiax** [comment]
> Hi @ztoiax
> Could you provide more detail code about the `device` ?
> `device` is `None` means that the device cannot be found on adb server.

Thank you. I have solved it.
