### ISSUE TITLE
device number?

### ISSUE THREAD

**Issue by selster** [Swind/pure-python-adb#5]
I can't figure out how to get the device number?  I can get it in android studio's terminal with adb devices.  And I can paste it into your example code, for instance:
from adb.client import Client as AdbClient
client = AdbClient(host="127.0.0.1", port=5037)
device = client.device("here I entered my device number")
device.push("c:\python36\scripts\d123.txt", "/sdcard/Download/d123.txt")

Should I be able to get the device number?
Thanks you, Steve

**Comment by selster** [comment]
It would be the equivalent of this:  subprocess.check_output(cmd).decode('utf8').strip().replace("List of devices attached","").strip()[:-7]

**Comment by selster** [comment]
on my windows 7 systems, shell gives me an error: 
device.shell("asdf")
'/system/bin/sh: asdf: not found\n'

In the meantime, this seems to work:

from adb.client import Client as AdbClient
import os
os.chdir(r'C:\Users\se\Downloads\scrcpy-win64-v1.5\scrcpy-win64')
import subprocess
cmd = "adb devices"
device = subprocess.check_output(cmd).decode('utf8').strip().replace("List of devices attached","").strip()[:-7]

client = AdbClient(host="127.0.0.1", port=5037)
device = client.device(device)
device.push("c:\python36\scripts\d123.txt", "/sdcard/Download/d1234.txt")

cmd2 = "adb shell ls /sdcard/Download/d1234.txt"
file_status = subprocess.check_output(cmd2).decode("utf8").strip()
print("the file is here: -->>  " + file_status)

**Comment by Swind** [comment]
Hi selster
You can use this to list all devices and get the serial number.

```
from adb.client import Client as AdbClient
client = AdbClient(host="127.0.0.1", port=5037)
devices = client.devices()

for device in devices:
    print(device.serial)
```
