### ISSUE TITLE
Is adb running on your computer?

### ISSUE THREAD

**Issue by YuvrajRaghuvanshiS** [Swind/pure-python-adb#69]
I am using your package to work on my project github.com/YuvrajRaghuvanshiS/Whatsapp-Key-Database-Extractor and replacing traditional ADB with ppadb however sometimes when I stop process in the middle it does not close process on it's own neither it does on re-run and I get stuck with 
`RuntimeError: ERROR: connecting to 127.0.0.1:5037 [WinError 10061] No connection could be made because the target machine actively refused it.`
`Is adb running on your computer?`
I'm uploading screenshot. Please let me know what am I missing because I could not seem to find an answer.
![image](https://user-images.githubusercontent.com/52948878/106358059-ddc1a400-632f-11eb-875a-4e26465fc829.png)

**Comment by jborbik** [comment]
Just run `adb devices` or any other command, it will start the server on you computer. https://developer.android.com/studio/command-line/adb

**Comment by YuvrajRaghuvanshiS** [comment]
Thank you for reply. Tried that but unfortunately did not work. 
My motive to use this insread of regular adb was to list devices instead of just printing them out on screen to create a menu like interface. I did that by working on lists. Here : https://raw.githubusercontent.com/YuvrajRaghuvanshiS/WhatsApp-Key-Database-Extractor/master/helpers/ADBDeviceSerialId.py
